### ISSUE TITLE
Release & Publish

### ISSUE THREAD

**Issue by cpcundill** [aistomin/jenkins-sdk#245]
Hey there!  

Great work so far, I can see you've already got decent coverage of the Jenkins API.  Do you plan to release anytime soon and publish to Maven central?

For now, I don't mind building and publishing to my own org's Nexus but wouldn't want to eventually know this can be pulled from Maven central.

Thanks!

**Comment by aistomin** [comment]
Hello @cpcundill! 
Thanks for your attention to my project, that's really motivates me :)
Yes, sure, the goal is to have it in Maven Central as soon as possible! I had a plan to finish this milestone: https://github.com/aistomin/jenkins-sdk/milestones/Basic%20version until the end of the March. Currently I have few real blockers, but I really hope to get it in maven central in the first days of April.

**Comment by aistomin** [comment]
@cpcundill Today I played a little bit with deploying. Currently test version `0.0.1` must be available in Maven Central. Could you please try to configure dependency in your project:
```
<dependencies>
        <dependency>
            <groupId>com.github.aistomin</groupId>
            <artifactId>jenkins-sdk</artifactId>
            <version>0.0.1</version>
        </dependency>
</dependencies>
```
That is really pre-release version, I plan to implement some cosmetic changes until this month and release version `0.1`. The interfaces will not be dramatically modified a meantime. That will be really working basic version :) 
I hope to finish with version `1.0` until the end of the year. There will be a long way to go :) Especially with my limited free time. 
Take a look at [examples project](https://github.com/aistomin/jenkins-sdk-examples), maybe it will also help you. 
Don't hesitate to ask any other questions if I can help you somehow. Feel free to close the issue if you're satisfied with answer/release.

**Comment by aistomin** [comment]
@cpcundill I'm glad to say that version `0.1` was released today. :)
